name: fl-py37
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.2
  - astroid=2.4.2
  - backcall=0.1.0
  - blas=1.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - cffi=1.14.0
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - decorator=4.4.2
  - freetype=2.9.1
  - intel-openmp=2020.0
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - isort=4.3.21
  - jedi=0.16.0
  - joblib=0.14.1
  - jpeg=9b
  - lazy-object-proxy=1.4.3
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - mccabe=0.6.1
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1g
  - pandas=1.0.1
  - parso=0.6.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=6.0.0
  - pip=20.0.2
  - prompt_toolkit=3.0.3
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.5.2
  - pylint=2.5.3
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytorch=1.1.0
  - pytz=2019.3
  - readline=7.0
  - scikit-learn=0.21.2
  - scipy=1.4.1
  - setuptools=46.0.0
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - toml=0.10.1
  - torchvision=0.3.0
  - traitlets=4.3.3
  - typed-ast=1.4.1
  - wcwidth=0.1.8
  - wheel=0.34.2
  - wrapt=1.11.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - torchsummary==1.5.1

